export const SuggestionNames = [
  { value: "john_doe", title: "John Doe" },
  { value: "jane_smith", title: "Jane Smith" },
  { value: "alex_jones", title: "Alex Jones" },
  { value: "emily_wilson", title: "Emily Wilson" },
  { value: "chris_miller", title: "Chris Miller" },
  { value: "sophia_roberts", title: "Sophia Roberts" },
  { value: "michael_brown", title: "Michael Brown" },
  { value: "olivia_taylor", title: "Olivia Taylor" },
  { value: "daniel_clark", title: "Daniel Clark" },
  { value: "ava_smith", title: "Ava Smith" },
  { value: "ryan_davis", title: "Ryan Davis" },
  { value: "ella_martin", title: "Ella Martin" },
  { value: "william_jackson", title: "William Jackson" },
  { value: "grace_hill", title: "Grace Hill" },
  { value: "matthew_anderson", title: "Matthew Anderson" },
  { value: "lily_carter", title: "Lily Carter" },
  { value: "james_wilson", title: "James Wilson" },
  { value: "emma_miller", title: "Emma Miller" },
  { value: "benjamin_turner", title: "Benjamin Turner" },
  { value: "chloe_smith", title: "Chloe Smith" },
];
